name: build search.sh script

on: 
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v4
      - name: building script
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: brew install shc
      - run: shc -f search.sh -o search
        shell: bash 
  
