name: build search.sh script

on: 
  push:
    branches: 
      - main
jobs:
  build-script:
    runs-on: macos-latest
    steps: 
      - name: checkout search.sh repo to this VM
        uses: actions/checkout@v4
      
      - name: install shc via brew
        run: | 
          brew --version
          brew install shc
          
      - name: comiple script
        run: shc -f search.sh -o search

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3.1.3
        with: 
          name: search binary
          path: ./search 

