name: build search.sh script

run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v4
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: brew install shc
      - run: shc -f search.sh -o search
      - shell: bash 
  
